IF NOT EXISTS(SELECT 1 FROM sys.Objects WHERE  Object_id = OBJECT_ID(N'dbo.BUSINESS_POLICYS') AND TYPE = N'U')
BEGIN
CREATE TABLE [dbo].[BUSINESS_POLICYS](
	[KEYNUM] [int] NOT NULL,
	[KEYNUMO] [int] NOT NULL,
	[CATGRY] [char](1) NOT NULL,
	[BUS] [bit] NOT NULL,
	[HNAME] [varchar](35) NOT NULL,
	[KEYNUMB] [int] NOT NULL,
	[RELATN] [char](10) NOT NULL,
	[REV_LOCN] [varchar](50) NOT NULL,
	[REV_DATE] [datetime] NOT NULL,
	[CR8_LOCN] [varchar](50) NOT NULL,
	[CR8_DATE] [datetime] NOT NULL,
	[DEL_] [bit] NOT NULL,
	[split] [numeric](5, 2) NULL,
	[Hsplit] [numeric](5, 2) NOT NULL,
	[Salesforce_Id] [char](18) NULL,
	[EMAILC]  AS ([dbo].[FUNC_Cinfo]([keynumb],[bus],'A.EMAIL')),
	[DPHONEBUSC]  AS ([dbo].[FUNC_Cinfo]([keynumb],[bus],'A.DPHONEBUS')),
	[PHONEBUSC]  AS ([dbo].[FUNC_Cinfo]([keynumb],[bus],'C.PHONEBUS')),
	[DPHONEEXTC]  AS ([dbo].[FUNC_Cinfo]([keynumb],[bus],'B.DPHONEEXT')),
	[islinked]  AS ([dbo].[FUNC_linkpol]([keynumb],[bus])),
	[hnamec]  AS ([dbo].[FUNC_hname]([keynumb],[bus],[hname],(5))),
 CONSTRAINT [PK_BUSINESS_POLICYS] PRIMARY KEY NONCLUSTERED 
(
	[KEYNUM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[BUSINESS_POLICYS] ADD  CONSTRAINT [FK_BUSINESS_POLICYS_BUSINESS] FOREIGN KEY (KEYNUMB) REFERENCES BUSINESS(KEYNUMB);

ALTER TABLE [dbo].[BUSINESS_POLICYS] ADD  CONSTRAINT [DF_BUSINESS_POLICYS_KEYNUMO]  DEFAULT ((0)) FOR [KEYNUMO]

ALTER TABLE [dbo].[BUSINESS_POLICYS] ADD  CONSTRAINT [DF_BUSINESS_POLICYS_CATGRY]  DEFAULT ('') FOR [CATGRY]

ALTER TABLE [dbo].[BUSINESS_POLICYS] ADD  CONSTRAINT [DF_BUSINESS_POLICYS_HNAME]  DEFAULT ('') FOR [HNAME]

ALTER TABLE [dbo].[BUSINESS_POLICYS] ADD  CONSTRAINT [DF_BUSINESS_POLICYS_KEYNUMB]  DEFAULT ((0)) FOR [KEYNUMB]

ALTER TABLE [dbo].[BUSINESS_POLICYS] ADD  CONSTRAINT [DF_BUSINESS_POLICYS_RELATN]  DEFAULT ('') FOR [RELATN]

ALTER TABLE [dbo].[BUSINESS_POLICYS] ADD  CONSTRAINT [DF_BUSINESS_POLICYS_REV_LOCN]  DEFAULT (suser_sname()) FOR [REV_LOCN]

ALTER TABLE [dbo].[BUSINESS_POLICYS] ADD  CONSTRAINT [DF_BUSINESS_POLICYS_REV_DATE]  DEFAULT (getdate()) FOR [REV_DATE]

ALTER TABLE [dbo].[BUSINESS_POLICYS] ADD  CONSTRAINT [DF_BUSINESS_POLICYS_CR8_LOCN]  DEFAULT (suser_sname()) FOR [CR8_LOCN]

ALTER TABLE [dbo].[BUSINESS_POLICYS] ADD  CONSTRAINT [DF_BUSINESS_POLICYS_CR8_DATE]  DEFAULT (getdate()) FOR [CR8_DATE]

ALTER TABLE [dbo].[BUSINESS_POLICYS] ADD  CONSTRAINT [DF_BUSINESS_POLICYS_DEL_]  DEFAULT ((0)) FOR [DEL_]

ALTER TABLE [dbo].[BUSINESS_POLICYS] ADD  CONSTRAINT [DF_BUSINESS_POLICYS_SPLIT]  DEFAULT ((0.0)) FOR [split]

ALTER TABLE [dbo].[BUSINESS_POLICYS] ADD  CONSTRAINT [DF_BUSINESS_POLICYS_HSPLIT]  DEFAULT ((0)) FOR [Hsplit]

ALTER TABLE [dbo].[BUSINESS_POLICYS]  WITH CHECK ADD  CONSTRAINT [CK_BUSINESS_POLICYS] CHECK  (([KEYNUM]>(0)))

ALTER TABLE [dbo].[BUSINESS_POLICYS] CHECK CONSTRAINT [CK_BUSINESS_POLICYS]

END

