ALTER TABLE [dbo].[BUSINESS_POLICYS] ADD  CONSTRAINT [FK_BUSINESS_POLICYS_BUSINESS] FOREIGN KEY (KEYNUMB) REFERENCES BUSINESS(KEYNUMB);

ALTER TABLE [dbo].[BUSINESS_POLICYS] ADD  CONSTRAINT [FK_BUSINESS_POLICYS_POLICYS] FOREIGN KEY (KEYNUMO) REFERENCES POLICYS(KEYNUMO);

ALTER TABLE [dbo].[BUSINESS_POLICYS] ADD  CONSTRAINT [DF_BUSINESS_POLICYS_KEYNUMO]  DEFAULT ((0)) FOR [KEYNUMO]

ALTER TABLE [dbo].[BUSINESS_POLICYS] ADD  CONSTRAINT [DF_BUSINESS_POLICYS_CATGRY]  DEFAULT ('') FOR [CATGRY]

ALTER TABLE [dbo].[BUSINESS_POLICYS] ADD  CONSTRAINT [DF_BUSINESS_POLICYS_HNAME]  DEFAULT ('') FOR [HNAME]

ALTER TABLE [dbo].[BUSINESS_POLICYS] ADD  CONSTRAINT [DF_BUSINESS_POLICYS_KEYNUMB]  DEFAULT ((0)) FOR [KEYNUMB]

ALTER TABLE [dbo].[BUSINESS_POLICYS] ADD  CONSTRAINT [DF_BUSINESS_POLICYS_RELATN]  DEFAULT ('') FOR [RELATN]

ALTER TABLE [dbo].[BUSINESS_POLICYS] ADD  CONSTRAINT [DF_BUSINESS_POLICYS_REV_LOCN]  DEFAULT (suser_sname()) FOR [REV_LOCN]

ALTER TABLE [dbo].[BUSINESS_POLICYS] ADD  CONSTRAINT [DF_BUSINESS_POLICYS_REV_DATE]  DEFAULT (getdate()) FOR [REV_DATE]

ALTER TABLE [dbo].[BUSINESS_POLICYS] ADD  CONSTRAINT [DF_BUSINESS_POLICYS_CR8_LOCN]  DEFAULT (suser_sname()) FOR [CR8_LOCN]

ALTER TABLE [dbo].[BUSINESS_POLICYS] ADD  CONSTRAINT [DF_BUSINESS_POLICYS_CR8_DATE]  DEFAULT (getdate()) FOR [CR8_DATE]

ALTER TABLE [dbo].[BUSINESS_POLICYS] ADD  CONSTRAINT [DF_BUSINESS_POLICYS_DEL_]  DEFAULT ((0)) FOR [DEL_]

ALTER TABLE [dbo].[BUSINESS_POLICYS] ADD  CONSTRAINT [DF_BUSINESS_POLICYS_SPLIT]  DEFAULT ((0.0)) FOR [split]

ALTER TABLE [dbo].[BUSINESS_POLICYS] ADD  CONSTRAINT [DF_BUSINESS_POLICYS_HSPLIT]  DEFAULT ((0)) FOR [Hsplit]

ALTER TABLE [dbo].[BUSINESS_POLICYS]  WITH CHECK ADD  CONSTRAINT [CK_BUSINESS_POLICYS] CHECK  (([KEYNUM]>(0)))

ALTER TABLE [dbo].[BUSINESS_POLICYS] CHECK CONSTRAINT [CK_BUSINESS_POLICYS]