ALTER TABLE [PEOPLE] DROP CONSTRAINT IF EXISTS CK_PEOPLE;
GO
IF NOT EXISTS(SELECT TOP 1 * FROM PEOPLE WHERE KEYNUMP = 0)
BEGIN
	INSERT INTO [dbo].[PEOPLE]
			   ([KEYNUMP]
			   ,[MR_MRS]
			   ,[FIRSTNAME]
			   ,[MIDNAME]
			   ,[GIVENNAME]
			   ,[SALUTE]
			   ,[LASTNAME]
			   ,[MAIDNAME]
			   ,[BIRTHDATE]
			   ,[SEX]
			   ,[AGENT1]
			   ,[AGENT2]
			   ,[AGENT3]
			   ,[AGENT4]
			   ,[AGENT5]
			   ,[STREET]
			   ,[CITY]
			   ,[PROV]
			   ,[POSTALCODE]
			   ,[SIN]
			   ,[SECRETARY]
			   ,[RECEPT]
			   ,[SEC_EXT]
			   ,[PHONEHOM]
			   ,[PHONECAR]
			   ,[DPHONEFAX]
			   ,[DPHONEBUS]
			   ,[PHONEOTH]
			   ,[OTHTYPE]
			   ,[SMOKER]
			   ,[OCCUPATION]
			   ,[CLIENTTYP]
			   ,[PSTATUS]
			   ,[SOURCE]
			   ,[EMAIL]
			   ,[EMAIL2]
			   ,[ETYPE2]
			   ,[GNOTES]
			   ,[BRNOTE]
			   ,[CLIENTDIR]
			   ,[PICPATH]
			   ,[CASE_STAGE]
			   ,[NETWORTH]
			   ,[REV_LOCN]
			   ,[REV_DATE]
			   ,[CR8_LOCN]
			   ,[CR8_DATE]
			   ,[SRCCAT]
			   ,[DEL_]
			   ,[TDATE]
			   ,[CNOTES]
			   ,[WEDDATE]
			   ,[HADDR]
			   ,[SCORE1]
			   ,[SCORE2]
			   ,[SCORE3]
			   ,[SCORE4]
			   ,[SCORE5]
			   ,[SCORE6]
			   ,[SCORE7]
			   ,[SCORE8]
			   ,[SCORE9]
			   ,[SCORE10]
			   ,[KOLBE]
			   ,[RELIGION]
			   ,[FCDFP]
			   ,[FCDFRB]
			   ,[FCDES]
			   ,[FCDFFP]
			   ,[FCDVS]
			   ,[FCDBL]
			   ,[FCDFL]
			   ,[PIN]
			   ,[svc_date]
			   ,[DEC_DATE]
			   ,[CASEAGENT1]
			   ,[PNOTES]
			   ,[FCDWS]
			   ,[FCDSA]
			   ,[FCDTR]
			   ,[MARKET]
			   ,[THIRDNAME]
			   ,[SVC_TYPE]
			   ,[Salesforce_Id])
		 VALUES
			   (
			   0
			   ,'Mr.'
			   ,'Zero'
			   ,''
			   ,1
			   ,'Zero'
			   ,'Zero'
			   ,''
			   ,NULL
			   ,'M'
			   ,''
			   ,''
			   ,''
			   ,''
			   ,''
			   ,''
			   ,''
			   ,''
			   ,''
			   ,''
			   ,''
			   ,''
			   ,''
			   ,''
			   ,''
			   ,''
			   ,''
			   ,''
			   ,''
			   ,''
			   ,'President'
			   ,'W'
			   ,''
			   ,'Telemagic'
			   ,''
			   ,''
			   ,''
			   ,''
			   ,''
			   ,''
			   ,''
			   ,0
			   ,0
			   ,'CM\Juliana'
			   ,'2019-07-05 12:21:02.000'
			   ,'CM\Juliana'
			   ,'2016-07-12 10:45:37.000'
			   ,''
			   ,'FALSE'
			   ,NULL
			   ,''
			   ,NULL
			   ,'FALSE'
			   ,0
			   ,0
			   ,0
			   ,0
			   ,0
			   ,0
			   ,0
			   ,0
			   ,0
			   ,0
			   ,''
			   ,''
			   ,''
			   ,''
			   ,''
			   ,''
			   ,''
			   ,''
			   ,''
			   ,''
			   ,'2018-01-01 00:00:00.000'
			   ,NULL
			   ,''
			   ,'Inserted Zero Key to apply FK on PEOPLE_POLICYS table'
			   ,''
			   ,''
			   ,''
			   ,''
			   ,''
			   ,''
			   ,''
			)
END


