IF (OBJECT_ID('FK_REL_BP_BUSINESS') IS NULL)
BEGIN
    ALTER TABLE [dbo].[REL_BP]
		ADD CONSTRAINT [FK_REL_BP_BUSINESS] FOREIGN KEY (KEYNUMB) REFERENCES BUSINESS(KEYNUMB);
END
GO

IF (OBJECT_ID('FK_REL_BP_PEOPLE') IS NULL)
BEGIN
    ALTER TABLE [dbo].[REL_BP]
		ADD CONSTRAINT [FK_REL_BP_PEOPLE] FOREIGN KEY (KEYNUMP) REFERENCES PEOPLE(KEYNUMP);
END
GO

