IF EXISTS(SELECT TOP 1 * FROM POL_ILL where KEYNUMO not in (select KEYNUMO from POLICYS))
BEGIN
	delete from POL_ILL where KEYNUMO not in (select KEYNUMO from POLICYS) -- 2492 -- IGNORE

	ALTER TABLE POL_ILL ADD CONSTRAINT FK_Policys_POL_ILL FOREIGN KEY (KEYNUMO) REFERENCES [dbo].[Policys](Keynumo)
END