IF (OBJECT_ID('DF_POLICYS_AGENT1') IS NOT NULL)
BEGIN
	
	SELECT *
	INTO POLICYS_BACKUP
	FROM POLICYS

	ALTER TABLE POLICYS DROP CONSTRAINT DF_POLICYS_AGENT1
	DROP INDEX IDX_POLICYS_AGENT1 ON POLICYS
	ALTER TABLE POLICYS DROP COLUMN AGENT1

	ALTER TABLE POLICYS DROP CONSTRAINT DF_POLICYS_AGENT2
	DROP INDEX IDX_POLICYS_AGENT2 ON POLICYS
	ALTER TABLE POLICYS DROP COLUMN AGENT2

	ALTER TABLE POLICYS DROP CONSTRAINT DF_POLICYS_AGENT3
	DROP INDEX IDX_POLICYS_AGENT3 ON POLICYS
	ALTER TABLE POLICYS DROP COLUMN AGENT3

	ALTER TABLE POLICYS DROP CONSTRAINT DF_POLICYS_AGENT4
	DROP INDEX IDX_POLICYS_AGENT4 ON POLICYS
	ALTER TABLE POLICYS DROP COLUMN AGENT4

	ALTER TABLE POLICYS DROP CONSTRAINT DF_POLICYS_AGENT5
	DROP INDEX IDX_POLICYS_AGENT5 ON POLICYS
	ALTER TABLE POLICYS DROP COLUMN AGENT5

	ALTER TABLE POLICYS DROP CONSTRAINT DF_POLICYS_AGENT6
	ALTER TABLE POLICYS DROP COLUMN AGENT6

	ALTER TABLE POLICYS DROP CONSTRAINT DF_POLICYS_SPLIT1
	ALTER TABLE POLICYS DROP COLUMN SPLIT1

	ALTER TABLE POLICYS DROP CONSTRAINT DF_POLICYS_SPLIT2
	ALTER TABLE POLICYS DROP COLUMN SPLIT2

	ALTER TABLE POLICYS DROP CONSTRAINT DF_POLICYS_SPLIT3
	ALTER TABLE POLICYS DROP COLUMN SPLIT3

	ALTER TABLE POLICYS DROP CONSTRAINT DF_POLICYS_SPLIT4
	ALTER TABLE POLICYS DROP COLUMN SPLIT4

	ALTER TABLE POLICYS DROP CONSTRAINT DF_POLICYS_SPLIT5
	ALTER TABLE POLICYS DROP COLUMN SPLIT5

	ALTER TABLE POLICYS DROP CONSTRAINT DF_POLICYS_SPLIT6
	ALTER TABLE POLICYS DROP COLUMN SPLIT6
END