IF NOT EXISTS(SELECT 1 FROM sys.Objects WHERE  Object_id = OBJECT_ID(N'dbo.COMM_BACKUP') AND TYPE = N'U')
BEGIN
	SELECT *
	INTO COMM_BACKUP
	FROM COMM	
END

IF EXISTS(SELECT 1 FROM sys.Objects WHERE  Object_id = OBJECT_ID(N'dbo.COMM_BACKUP') AND TYPE = N'U')
BEGIN
	IF EXISTS(SELECT 1 FROM sys.Objects WHERE  Object_id = OBJECT_ID(N'dbo.COMM') AND TYPE = N'U')
	BEGIN
		DROP TABLE COMM
	END
END

IF NOT EXISTS(SELECT 1 FROM sys.Objects WHERE  Object_id = OBJECT_ID(N'dbo.COMM') AND TYPE = N'U')
BEGIN
	EXEC sp_rename 'dbo.Commission', 'COMM';
END